<?php
namespace app\home\controller;

use think\Session;

class Index extends HomeBase
{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return view('index');
    }
}
