<?php
namespace app\home\controller;

use think\Loader;
use think\Session;
use think\View;


class Users  extends  HomeBase
{
    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub

    }
//    登录
    public function login()
    {
        $msg='';
        if (isset($_POST['username']) && isset($_POST['password'])){
            $data['user_name']=$_POST['username'];
            $data['user_password']=$_POST['password'];
           // 数据库中查找用户信息是否存在
            $user=Loader::model('Users');

            $res=$user->getUserDatas($data);

            if($res){
                Session::set('username',$res['user_name']);
                //dump(Session::get('username')) ;
                return $this->redirect('Index/index');//redirect参数格式 控制器/方法

            }else{

                $msg="用户名密码错误";

                return $this->fetch('login',['msg'=>$msg]);//redirect参数格式 控制器/方法

            }


        }else{
            return $this->fetch('login',['msg'=>$msg]);//redirect参数格式 控制器/方法

        }
    }

    public function logout(){
        Session::delete('username');
        return redirect('login');//redirect参数格式 控制器/方法

    }
//    获得用户列表返回用户名 id
    public function getUserNameList(){
        $user=Loader::model('Users');
        $req[0]='real_name';
        $req[1]='id';
        $res=$user->requirementSelect($req);
        return json($res);
    }
}
